# INITNIAL SETTINGS
train_path: ./train_augmented_4.csv
dev_path: ../data/dev.csv
test_path: ../data/dev.csv
predict_path: ../data/test.csv
model_name: monologg/koelectra-base-v3-discriminator
fine_tuning: False

# Parameters
batch_size: 64
max_epoch: 10
learning_rate: 1e-5
shuffle: True

# WandB
project_name: 'sts-back_translation'
log_name: True
save_dir: '../wandb'

# Fine-tuning
checkpoint_name: sts-epoch=19-val_pearson=0.79
