## snunlp/KR-ELECTRA-discriminator

# Model
name: KR-ELECTRA-discriminator
model_name: snunlp/KR-ELECTRA-discriminator

# System
accelerator: gpu
gpu_num: 1

# Trainer
learning_rate: 0.0000619
max_epoch: 60
batch_size: 256
max_sentence_length: 100
shuffle: True

# Data
train_path: ../data/train.csv
dev_path: ../data/dev.csv
test_path: ../data/dev.csv
predict_path: ../data/test.csv
